import { setAudioModeAsync, useAudioPlayer, type AudioPlayer } from 'expo-audio';
import { useCallback, useMemo } from 'react';
import { Platform } from 'react-native';

// Generated by scripts/make-sounds.py
const SOURCES = {
  bell: require('../../assets/sounds/bell.wav'),
  chime: require('../../assets/sounds/chime.wav'),
  inhale: require('../../assets/sounds/inhale.wav'),
  exhale: require('../../assets/sounds/exhale.wav'),
};

export type SoundEffect = keyof typeof SOURCES;

let configured = false;

export function configureAudio() {
  if (configured) return;
  configured = true;
  setAudioModeAsync({
    // On iPhone the silent switch silences the app, so a session never surprises someone in public.
    // Android has no such switch for media; the media volume decides.
    playsInSilentMode: Platform.OS !== 'ios',
    // Chimes play over the user's own music or podcast instead of stopping it.
    interruptionMode: 'mixWithOthers',
  }).catch(() => {});
}

/** Session bells and breath cues. play() does nothing while effects are turned off. */
export function useSoundEffects(enabled: boolean) {
  const bell = useAudioPlayer(SOURCES.bell);
  const chime = useAudioPlayer(SOURCES.chime);
  const inhale = useAudioPlayer(SOURCES.inhale);
  const exhale = useAudioPlayer(SOURCES.exhale);
  const players = useMemo<Record<SoundEffect, AudioPlayer>>(() => ({ bell, chime, inhale, exhale }), [bell, chime, inhale, exhale]);

  const play = useCallback(
    (effect: SoundEffect) => {
      if (!enabled) return;
      configureAudio();
      const player = players[effect];
      player.seekTo(0).catch(() => {});
      player.play();
    },
    [enabled, players],
  );

  return play;
}
