import { setAudioModeAsync, useAudioPlayer, type AudioPlayer } from 'expo-audio';
import { useCallback, useEffect, useMemo, useRef } from 'react';
import { Platform } from 'react-native';

// Generated by scripts/make-sounds.py
const SOURCES = {
  bell: require('../../assets/sounds/bell.wav'),
  chime: require('../../assets/sounds/chime.wav'),
  inhale: require('../../assets/sounds/inhale.wav'),
  exhale: require('../../assets/sounds/exhale.wav'),
};

export type SoundEffect = keyof typeof SOURCES;

let configured = false;

export function configureAudio() {
  if (configured) return;
  configured = true;
  setAudioModeAsync({
    // On iPhone the silent switch silences the app, so a session never surprises someone in public.
    // Android has no such switch for media; the media volume decides.
    playsInSilentMode: Platform.OS !== 'ios',
    // Chimes play over the user's own music or podcast instead of stopping it.
    interruptionMode: 'mixWithOthers',
  }).catch(() => {});
}

/** Session bells and breath cues. play() does nothing while effects are turned off. */
export function useSoundEffects(enabled: boolean) {
  const bell = useAudioPlayer(SOURCES.bell);
  const chime = useAudioPlayer(SOURCES.chime);
  const inhale = useAudioPlayer(SOURCES.inhale);
  const exhale = useAudioPlayer(SOURCES.exhale);
  const players = useMemo<Record<SoundEffect, AudioPlayer>>(() => ({ bell, chime, inhale, exhale }), [bell, chime, inhale, exhale]);

  const play = useCallback(
    (effect: SoundEffect) => {
      if (!enabled) return;
      configureAudio();
      const player = players[effect];
      player.seekTo(0).catch(() => {});
      player.play();
    },
    [enabled, players],
  );

  return play;
}

// The player is a native object controlled through its properties; setting them in helpers
// keeps React's lint rules from treating it as hook state.
function setVolume(player: AudioPlayer, volume: number) {
  player.volume = volume;
}

function setLoop(player: AudioPlayer) {
  player.loop = true;
}

/**
 * Loops background music while `playing`, fading in and out instead of starting or stopping
 * abruptly. Changing `volume` glides to the new level, which is how music ducks under the voice.
 */
export function useBackgroundMusic(source: string | null, playing: boolean, volume: number) {
  const player = useAudioPlayer(source);
  const level = useRef(0);

  useEffect(() => {
    setLoop(player);
    setVolume(player, 0);
    level.current = 0;
  }, [player]);

  useEffect(() => {
    if (!source) return;
    const target = playing ? volume : 0;
    if (playing) {
      configureAudio();
      setVolume(player, level.current);
      player.play();
    }
    const timer = setInterval(() => {
      const gap = target - level.current;
      level.current = Math.abs(gap) <= 0.03 ? target : level.current + Math.sign(gap) * 0.03;
      setVolume(player, level.current);
      if (level.current === target) {
        clearInterval(timer);
        if (!playing) player.pause();
      }
    }, 60);
    return () => clearInterval(timer);
  }, [player, source, playing, volume]);
}
